ALTER TABLE users COMMENT '用户表';
ALTER TABLE users 
  MODIFY COLUMN openid VARCHAR(100) COMMENT '微信openid',
  MODIFY COLUMN unionid VARCHAR(100) COMMENT '微信unionid',
  MODIFY COLUMN nickname VARCHAR(100) COMMENT '昵称',
  MODIFY COLUMN avatar_url VARCHAR(500) COMMENT '头像URL',
  MODIFY COLUMN phone VARCHAR(20) COMMENT '手机号',
  MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE query_pages COMMENT '查询页面表';
ALTER TABLE query_pages
  MODIFY COLUMN user_id VARCHAR(36) NOT NULL COMMENT '创建用户ID',
  MODIFY COLUMN name VARCHAR(200) NOT NULL COMMENT '查询名称',
  MODIFY COLUMN description TEXT COMMENT '查询描述',
  MODIFY COLUMN cover_url VARCHAR(500) COMMENT '封面图URL',
  MODIFY COLUMN status ENUM('pending', 'active', 'ended') DEFAULT 'active' COMMENT '状态：待发布/进行中/已结束',
  MODIFY COLUMN settings JSON COMMENT '查询设置(JSON格式)',
  MODIFY COLUMN start_time TIMESTAMP NULL COMMENT '开始时间',
  MODIFY COLUMN end_time TIMESTAMP NULL COMMENT '结束时间',
  MODIFY COLUMN query_limit INT DEFAULT 0 COMMENT '查询次数限制，0表示不限制',
  MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE query_data COMMENT '查询数据表';
ALTER TABLE query_data
  MODIFY COLUMN query_page_id VARCHAR(36) NOT NULL COMMENT '所属查询页面ID',
  MODIFY COLUMN row_index INT NOT NULL COMMENT '行索引',
  MODIFY COLUMN data JSON NOT NULL COMMENT '当前数据(JSON格式)',
  MODIFY COLUMN original_data JSON COMMENT '原始数据(JSON格式)',
  MODIFY COLUMN is_modified BOOLEAN DEFAULT FALSE COMMENT '是否已修改',
  MODIFY COLUMN modified_at TIMESTAMP NULL COMMENT '最后修改时间',
  MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE query_headers COMMENT '查询表头配置表';
ALTER TABLE query_headers
  MODIFY COLUMN query_page_id VARCHAR(36) NOT NULL COMMENT '所属查询页面ID',
  MODIFY COLUMN column_index INT NOT NULL COMMENT '列索引',
  MODIFY COLUMN column_name VARCHAR(100) NOT NULL COMMENT '列名称',
  MODIFY COLUMN is_condition BOOLEAN DEFAULT FALSE COMMENT '是否为查询条件',
  MODIFY COLUMN is_modifiable BOOLEAN DEFAULT FALSE COMMENT '是否允许修改',
  MODIFY COLUMN is_hidden BOOLEAN DEFAULT FALSE COMMENT '是否隐藏',
  MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE query_records COMMENT '查询记录表';
ALTER TABLE query_records
  MODIFY COLUMN query_page_id VARCHAR(36) NOT NULL COMMENT '所属查询页面ID',
  MODIFY COLUMN query_data_id INT NOT NULL COMMENT '查询的数据ID',
  MODIFY COLUMN user_id VARCHAR(36) COMMENT '查询用户ID',
  MODIFY COLUMN openid VARCHAR(100) COMMENT '查询用户openid',
  MODIFY COLUMN query_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '查询时间',
  MODIFY COLUMN query_count INT DEFAULT 1 COMMENT '查询次数';

ALTER TABLE signatures COMMENT '签收记录表';
ALTER TABLE signatures
  MODIFY COLUMN query_page_id VARCHAR(36) NOT NULL COMMENT '所属查询页面ID',
  MODIFY COLUMN query_data_id INT NOT NULL COMMENT '签收的数据ID',
  MODIFY COLUMN user_id VARCHAR(36) COMMENT '签收用户ID',
  MODIFY COLUMN openid VARCHAR(100) COMMENT '签收用户openid',
  MODIFY COLUMN sign_type ENUM('signature', 'button') DEFAULT 'button' COMMENT '签收方式：手写签名/按钮确认',
  MODIFY COLUMN signature_url VARCHAR(500) COMMENT '签名图片URL',
  MODIFY COLUMN signed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '签收时间';

ALTER TABLE data_modifications COMMENT '数据修改记录表';
ALTER TABLE data_modifications
  MODIFY COLUMN query_data_id INT NOT NULL COMMENT '被修改的数据ID',
  MODIFY COLUMN column_name VARCHAR(100) NOT NULL COMMENT '修改的列名',
  MODIFY COLUMN old_value TEXT COMMENT '修改前的值',
  MODIFY COLUMN new_value TEXT COMMENT '修改后的值',
  MODIFY COLUMN modified_by VARCHAR(36) COMMENT '修改人openid',
  MODIFY COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间';

ALTER TABLE export_records COMMENT '导出记录表';
ALTER TABLE export_records
  MODIFY COLUMN user_id VARCHAR(36) NOT NULL COMMENT '导出用户ID',
  MODIFY COLUMN query_page_id VARCHAR(36) COMMENT '导出的查询页面ID',
  MODIFY COLUMN file_name VARCHAR(200) COMMENT '导出文件名',
  MODIFY COLUMN file_path VARCHAR(500) COMMENT '导出文件路径',
  MODIFY COLUMN export_type ENUM('data') DEFAULT 'data' COMMENT '导出类型：数据导出',
  MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '导出时间';

ALTER TABLE favorites COMMENT '收藏表';
ALTER TABLE favorites
  MODIFY COLUMN user_id VARCHAR(36) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN query_page_id VARCHAR(36) NOT NULL COMMENT '查询页面ID',
  MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '收藏时间';

ALTER TABLE feedback COMMENT '用户反馈表';
ALTER TABLE feedback
  MODIFY COLUMN user_id VARCHAR(36) COMMENT '用户ID',
  MODIFY COLUMN type ENUM('bug', 'feature', 'other') DEFAULT 'other' COMMENT '反馈类型：Bug反馈/功能建议/其他',
  MODIFY COLUMN content TEXT NOT NULL COMMENT '反馈内容',
  MODIFY COLUMN images JSON COMMENT '反馈图片(JSON数组)',
  MODIFY COLUMN contact VARCHAR(100) COMMENT '联系方式',
  MODIFY COLUMN status ENUM('pending', 'processing', 'done') DEFAULT 'pending' COMMENT '处理状态：待处理/处理中/已完成',
  MODIFY COLUMN reply TEXT COMMENT '回复内容',
  MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
