ALTER TABLE query_pages 
ADD COLUMN IF NOT EXISTS allow_modify BOOLEAN DEFAULT FALSE COMMENT '是否允许修改信息',
ADD COLUMN IF NOT EXISTS enable_sign BOOLEAN DEFAULT FALSE COMMENT '是否开启签收',
ADD COLUMN IF NOT EXISTS require_nickname BOOLEAN DEFAULT FALSE COMMENT '查询时是否需授权昵称',
ADD COLUMN IF NOT EXISTS query_limit INT DEFAULT 0 COMMENT '查询次数限制，0表示不限制',
ADD COLUMN IF NOT EXISTS query_time_limit TIMESTAMP NULL COMMENT '查询时间限制，NULL表示不限制',
ADD COLUMN IF NOT EXISTS start_time TIMESTAMP NULL COMMENT '开始时间',
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP NULL COMMENT '结束时间';

ALTER TABLE export_records
MODIFY COLUMN export_type ENUM('data') DEFAULT 'data' COMMENT '导出类型：数据导出';
